name: 'Code Quality Checks'

on:
  push:
    branches:
      - '*'
      - '!main'
  pull_request:
    branches: ['*']

jobs:
  quality_checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - name: Check formatting with Prettier
        run: npm run format
      - name: Lint with ESLint
        run: npm run lint
      - name: Perform unit & component tests with Vitest
        run: npm run test
