name: 'Code Quality Checks'

on:
  push:
    branches:
      - '*'
      - '!main'
  pull_request:
    branches: ['*']

env:
  CI: true
  VITE_GITHUB_USERNAME: ${{ vars.VITE_GITHUB_USERNAME }}
  VITE_GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}

jobs:
  quality_checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node & pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.4.1
          run_install: |
            - recursive: true
              args: [--frozen-lockfile]
      - name: Typecheck with TypeScript
        run: npm run typecheck
      - name: Check formatting with Prettier
        run: pnpm run format
      - name: Lint with ESLint
        run: pnpm run lint
      - name: Run unit tests
        run: pnpm run test
